<?php

namespace Greendot\EshopBundle\Enum;

enum TransportationExportNameEnum: string
{

    case HEUREKA = 'heureka';
    case ZBOZI = 'zbozi';
//    case GOOGLE = 'google';

    public function available(): array
    {
        return match ($this){
            self::HEUREKA => ['CESKA_POSTA','CESKA_POSTA_DOPORUCENA_ZASILKA','CSAD_LOGISTIK_OSTRAVA','DPD','DHL','DSV','FOFR','GEBRUDER_WEISS','GEIS','GLS','PPL','SEEGMULLER','TOPTRANS','UPS','FEDEX','RABEN_LOGISTICS','ZASILKOVNA_NA_ADRESU','ONE_COURIER','RHENUS_LOGISTICS','MESSENGER','BALIKOVNA_NA_ADRESU','QDL','DB_SCHENKER','EMONS','ZASILKOVNA','DPD_PICKUP','BALIKOVNA_DEPOTAPI','ONE_POINT','PPL_PARCELSHOP','GLS_PARCELSHOP','ALZAPOINT','UPS_ACCESS_POINT','DPD_BOX','Z_BOX','ONE_BOX','PPL_PARCELBOX','BALIKOVNA_BOX','ALZABOX','GLS_PARCELBOX','ONLINE','VLASTNI_PREPRAVA'],
            self::ZBOZI => ['ALZABOX','CESKA_POSTA_BALIKOVNA','CESKA_POSTA_NA_POSTU','DPD_PICKUP','GLS_PARCELSHOP','PPL_PARCELSHOP','TOPTRANS_DEPO','ONE_POINT','ZASILKOVNA','VLASTNI_VYDEJNI_MISTA','123_KURYR','CESKA_POSA','BALIKOVNA_NA_ADRESU','DACHSER','DB_SCHENKER','DPD','DHL','DSV','EMONS','FOFR','GEBRUDER_WEISS','GEIS','GLS','HDS','HELICAR','IN_TIME_KURYR','ONE_COURIER','NAS_KURYR','MESSENGER','LAGERMAX','PPL','TNT','TOPTRANS','UPS','FEDEX','RABEN_LOGISTICS','RHENUS','ZASILKOVNA_NA_ADRESU','VLASTNI_PREPRAVA'],
//            self::GOOGLE => [],
            default => []
        };
    }

}
