<?php

namespace Greendot\EshopBundle\Tests\Parcel\MessageHandler;

use DateTimeImmutable;
use PHPUnit\Framework\TestCase;
use Psr\Log\NullLogger;
use Symfony\Component\Workflow\TransitionBlockerList;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\Messenger\Envelope;
use Symfony\Component\Messenger\MessageBusInterface;
use Symfony\Component\Messenger\Stamp\DelayStamp;
use Symfony\Component\Workflow\WorkflowInterface;
use Greendot\EshopBundle\Entity\Project\Purchase;
use Greendot\EshopBundle\Entity\Project\TransportationEvent;
use Greendot\EshopBundle\Parcel\ParcelDeliveryStateEnum;
use Greendot\EshopBundle\Parcel\ParcelServiceInterface;
use Greendot\EshopBundle\Parcel\ParcelServiceProviderInterface;
use Greendot\EshopBundle\Parcel\ParcelStatusInfoDto;
use Greendot\EshopBundle\Parcel\Exception\ParcelServiceNotFoundException;
use Greendot\EshopBundle\Parcel\Message\UpdateDeliveryStatusMessage;
use Greendot\EshopBundle\Parcel\MessageHandler\UpdateDeliveryStatusHandler;
use Greendot\EshopBundle\Repository\Project\PurchaseRepository;
use Greendot\EshopBundle\Repository\Project\TransportationEventRepository;
use Greendot\EshopBundle\Workflow\PurchaseWorkflowContract as PWC;
use Symfony\Component\Messenger\Exception\RecoverableMessageHandlingException;
use Symfony\Component\Messenger\Exception\UnrecoverableMessageHandlingException;

class UpdateDeliveryStatusHandlerTest extends TestCase
{
    private PurchaseRepository $purchaseRepo;
    private TransportationEventRepository $eventRepo;
    private ParcelServiceProviderInterface $provider;
    private EntityManagerInterface $em;
    private MessageBusInterface $bus;
    private WorkflowInterface $workflow;
    private UpdateDeliveryStatusHandler $handler;

    protected function setUp(): void
    {
        $this->purchaseRepo = $this->createMock(PurchaseRepository::class);
        $this->eventRepo    = $this->createMock(TransportationEventRepository::class);
        $this->provider     = $this->createMock(ParcelServiceProviderInterface::class);
        $this->em           = $this->createMock(EntityManagerInterface::class);
        $this->bus          = $this->createMock(MessageBusInterface::class);
        $this->workflow     = $this->createMock(WorkflowInterface::class);

        // TransitionBlockerList is final — cannot be auto-generated by PHPUnit mock; stub it explicitly
        $this->workflow->method('buildTransitionBlockerList')
            ->willReturn(new TransitionBlockerList());

        $this->handler = new UpdateDeliveryStatusHandler(
            $this->provider,
            $this->purchaseRepo,
            $this->eventRepo,
            $this->em,
            $this->bus,
            new NullLogger(),
            $this->workflow,
        );
    }

    private function makeMsg(int $id = 1): UpdateDeliveryStatusMessage
    {
        return new UpdateDeliveryStatusMessage($id);
    }

    private function makePurchase(int $daysOld = 0): Purchase
    {
        $purchase = $this->createMock(Purchase::class);
        $purchase->method('getId')->willReturn(1);
        $purchase->method('getDateIssue')->willReturn(
            new DateTimeImmutable("-$daysOld days")
        );
        return $purchase;
    }

    private function makeEvent(
        ParcelDeliveryStateEnum $state,
        ?DateTimeImmutable $occurredAt = null,
    ): TransportationEvent {
        $event = $this->createMock(TransportationEvent::class);
        $event->method('getState')->willReturn($state);
        $event->method('getOccurredAt')->willReturn($occurredAt);
        return $event;
    }

    private function makeService(ParcelStatusInfoDto $dto): ParcelServiceInterface
    {
        $service = $this->createMock(ParcelServiceInterface::class);
        $service->method('getParcelStatus')->willReturn($dto);
        return $service;
    }

    // --- Guard: purchase not found ---

    public function testPurchaseNotFound_throwsUnrecoverable(): void
    {
        $this->purchaseRepo->method('find')->willReturn(null);
        $this->expectException(UnrecoverableMessageHandlingException::class);
        ($this->handler)($this->makeMsg());
    }

    // --- Guard: final state ---

    public function testFinalState_returnsEarlyWithoutDispatch(): void
    {
        $purchase = $this->makePurchase();
        $this->purchaseRepo->method('find')->willReturn($purchase);
        $finalEvent = $this->makeEvent(ParcelDeliveryStateEnum::DELIVERED);
        $this->eventRepo->method('findLatestByPurchase')->willReturn($finalEvent);

        $this->bus->expects($this->never())->method('dispatch');
        $this->em->expects($this->never())->method('persist');

        ($this->handler)($this->makeMsg());
    }

    // --- Guard: polling window expired ---

    public function testExpiredPollingWindow_returnsEarlyWithoutDispatch(): void
    {
        $purchase = $this->makePurchase(daysOld: 15);
        $this->purchaseRepo->method('find')->willReturn($purchase);
        $this->eventRepo->method('findLatestByPurchase')->willReturn(null);

        $this->bus->expects($this->never())->method('dispatch');

        ($this->handler)($this->makeMsg());
    }

    // --- Guard: no parcel service ---

    public function testNoParcelService_throwsUnrecoverable(): void
    {
        $purchase = $this->makePurchase();
        $this->purchaseRepo->method('find')->willReturn($purchase);
        $this->eventRepo->method('findLatestByPurchase')->willReturn(null);
        $this->provider->method('getByPurchase')->willThrowException(new ParcelServiceNotFoundException());

        $this->expectException(UnrecoverableMessageHandlingException::class);
        ($this->handler)($this->makeMsg());
    }

    // --- Guard: transient provider error ---

    public function testProviderThrows_throwsRecoverable(): void
    {
        $purchase = $this->makePurchase();
        $this->purchaseRepo->method('find')->willReturn($purchase);
        $this->eventRepo->method('findLatestByPurchase')->willReturn(null);
        $service = $this->createMock(ParcelServiceInterface::class);
        $service->method('getParcelStatus')->willThrowException(new \RuntimeException('timeout'));
        $this->provider->method('getByPurchase')->willReturn($service);

        $this->expectException(RecoverableMessageHandlingException::class);
        ($this->handler)($this->makeMsg());
    }

    // --- Deduplication ---

    public function testNoStatusChange_doesNotPersist(): void
    {
        $ts = new DateTimeImmutable('2024-01-10T12:00:00');
        $purchase = $this->makePurchase();
        $this->purchaseRepo->method('find')->willReturn($purchase);
        $lastEvent = $this->makeEvent(ParcelDeliveryStateEnum::IN_TRANSIT, $ts);
        $this->eventRepo->method('findLatestByPurchase')->willReturn($lastEvent);

        $dto = new ParcelStatusInfoDto(ParcelDeliveryStateEnum::IN_TRANSIT, [], $ts);
        $this->provider->method('getByPurchase')->willReturn($this->makeService($dto));
        $this->bus->method('dispatch')->willReturn(new Envelope(new \stdClass()));
        $this->workflow->method('can')->willReturn(false);

        $this->em->expects($this->never())->method('persist');
        ($this->handler)($this->makeMsg());
    }

    public function testSameStateEqualTimestamp_doesNotDuplicate(): void
    {
        // Two distinct DateTimeImmutable objects with the same value must be treated as equal
        $ts1 = new DateTimeImmutable('2024-03-15T09:30:00');
        $ts2 = new DateTimeImmutable('2024-03-15T09:30:00');
        $this->assertNotSame($ts1, $ts2, 'precondition: distinct objects');
        $this->assertEquals($ts1, $ts2, 'precondition: same value');

        $purchase = $this->makePurchase();
        $this->purchaseRepo->method('find')->willReturn($purchase);
        $lastEvent = $this->makeEvent(ParcelDeliveryStateEnum::IN_TRANSIT, $ts1);
        $this->eventRepo->method('findLatestByPurchase')->willReturn($lastEvent);

        $dto = new ParcelStatusInfoDto(ParcelDeliveryStateEnum::IN_TRANSIT, [], $ts2);
        $this->provider->method('getByPurchase')->willReturn($this->makeService($dto));
        $this->bus->method('dispatch')->willReturn(new Envelope(new \stdClass()));
        $this->workflow->method('can')->willReturn(false);

        $this->em->expects($this->never())->method('persist');
        ($this->handler)($this->makeMsg());
    }

    // --- Event persistence ---

    public function testStatusChanged_persistsNewEvent(): void
    {
        $purchase = $this->makePurchase();
        $this->purchaseRepo->method('find')->willReturn($purchase);
        $lastEvent = $this->makeEvent(ParcelDeliveryStateEnum::RECEIVED_DATA);
        $this->eventRepo->method('findLatestByPurchase')->willReturn($lastEvent);

        $dto = new ParcelStatusInfoDto(ParcelDeliveryStateEnum::IN_TRANSIT);
        $this->provider->method('getByPurchase')->willReturn($this->makeService($dto));
        $this->bus->method('dispatch')->willReturn(new Envelope(new \stdClass()));
        $this->workflow->method('can')->willReturn(false);

        $this->em->expects($this->once())->method('persist')
            ->with($this->isInstanceOf(TransportationEvent::class));
        ($this->handler)($this->makeMsg());
    }

    // --- Workflow transitions ---

    public function testInTransit_appliesLogSendTransition(): void
    {
        $purchase = $this->makePurchase();
        $this->purchaseRepo->method('find')->willReturn($purchase);
        $this->eventRepo->method('findLatestByPurchase')->willReturn(null);

        $dto = new ParcelStatusInfoDto(ParcelDeliveryStateEnum::IN_TRANSIT);
        $this->provider->method('getByPurchase')->willReturn($this->makeService($dto));
        $this->bus->method('dispatch')->willReturn(new Envelope(new \stdClass()));
        $this->workflow->method('can')->willReturn(true);

        $this->workflow->expects($this->once())->method('apply')
            ->with($purchase, PWC::T_LOG_SEND->value);
        ($this->handler)($this->makeMsg());
    }

    public function testDelivered_appliesLogDeliverTransition(): void
    {
        $purchase = $this->makePurchase();
        $this->purchaseRepo->method('find')->willReturn($purchase);
        $this->eventRepo->method('findLatestByPurchase')->willReturn(null);

        $dto = new ParcelStatusInfoDto(ParcelDeliveryStateEnum::DELIVERED);
        $this->provider->method('getByPurchase')->willReturn($this->makeService($dto));
        $this->workflow->method('can')->willReturn(true);

        $this->workflow->expects($this->once())->method('apply')
            ->with($purchase, PWC::T_LOG_DELIVER->value);
        ($this->handler)($this->makeMsg());
    }

    // --- Rescheduling ---

    public function testFinalStatus_doesNotReschedule(): void
    {
        $purchase = $this->makePurchase();
        $this->purchaseRepo->method('find')->willReturn($purchase);
        $this->eventRepo->method('findLatestByPurchase')->willReturn(null);

        $dto = new ParcelStatusInfoDto(ParcelDeliveryStateEnum::DELIVERED);
        $this->provider->method('getByPurchase')->willReturn($this->makeService($dto));
        $this->workflow->method('can')->willReturn(false);

        $this->bus->expects($this->never())->method('dispatch');
        ($this->handler)($this->makeMsg());
    }

    public function testNonFinalStatus_reschedules(): void
    {
        $purchase = $this->makePurchase();
        $this->purchaseRepo->method('find')->willReturn($purchase);
        $this->eventRepo->method('findLatestByPurchase')->willReturn(null);

        $dto = new ParcelStatusInfoDto(ParcelDeliveryStateEnum::IN_TRANSIT);
        $this->provider->method('getByPurchase')->willReturn($this->makeService($dto));
        $this->workflow->method('can')->willReturn(false);

        $dispatchedEnvelope = null;
        $this->bus->expects($this->once())->method('dispatch')
            ->willReturnCallback(function (UpdateDeliveryStatusMessage $msg, array $stamps) use (&$dispatchedEnvelope) {
                $this->assertSame(1, $msg->purchaseId);
                $this->assertCount(1, $stamps);
                $this->assertInstanceOf(DelayStamp::class, $stamps[0]);
                $dispatchedEnvelope = new Envelope($msg);
                return $dispatchedEnvelope;
            });

        ($this->handler)($this->makeMsg());
    }

    // --- Flush after transition ---

    public function testFlushCalledAfterTransition(): void
    {
        $purchase = $this->makePurchase();
        $this->purchaseRepo->method('find')->willReturn($purchase);
        $this->eventRepo->method('findLatestByPurchase')->willReturn(null);

        $dto = new ParcelStatusInfoDto(ParcelDeliveryStateEnum::DELIVERED);
        $this->provider->method('getByPurchase')->willReturn($this->makeService($dto));
        $this->workflow->method('can')->willReturn(true);

        // flush() must be called: once after persist (skipped — no event persisted since lastEvent is null
        // and state changed from null), and once after the transition block
        $this->em->expects($this->atLeastOnce())->method('flush');
        ($this->handler)($this->makeMsg());
    }
}
