#Upload
ALTER TABLE event ADD upload_id INT DEFAULT NULL;
ALTER TABLE event ADD CONSTRAINT FK_3BAE0AA7CCCFBA31 FOREIGN KEY (upload_id) REFERENCES upload (id);
CREATE INDEX IDX_3BAE0AA7CCCFBA31 ON event (upload_id);

#event_person
CREATE TABLE event_person (id INT AUTO_INCREMENT NOT NULL, event_id INT DEFAULT NULL, person_id INT DEFAULT NULL, sequence INT NOT NULL, INDEX IDX_645A62471F7E88B (event_id), INDEX IDX_645A624217BBB47 (person_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB;
ALTER TABLE event_person ADD CONSTRAINT FK_645A62471F7E88B FOREIGN KEY (event_id) REFERENCES event (id);
ALTER TABLE event_person ADD CONSTRAINT FK_645A624217BBB47 FOREIGN KEY (person_id) REFERENCES person (id);

#parameter
ALTER TABLE parameter ADD event_id INT DEFAULT NULL;
ALTER TABLE parameter ADD CONSTRAINT FK_2A97911071F7E88B FOREIGN KEY (event_id) REFERENCES event (id);